language: ruby
rvm:
- 2.2.0
install:
- travis_retry gem install s3_website -v 2.12.2
- travis_retry npm install
before_script: webpack
script: deploy/s3_deploy.sh
cache:
  bundler: true
  directories:
    - node_modules
env:
  global:
  - secure: IfFxjZpGxONdgoVoTLStYCLwMym6pIP+R/WgU6DkVNa0SMlu6dJygq9551IEDmESOgVcQlJdS0tKcvgGD+cFyaU2K0gnWilhWm+/glcYVhExjh0EWGziyR5Yk9lbVzj251bj28oFJDEYOmuxfUMxmK/P/6Lu3xU5S7lRJLNtpQysyWCxxbyipT9tazXiMnw9V/fKS2xf4MAxfQnF1J8nxo1o7jJcKilDgOg7h/c/D4qRXdvOS3caTZnaQaX/RybrfI5xMSyo3oOa1dNC/JlYFHW7UTm+XgOwlbFfWbRN6zuGdPAaJM4vuL2wNXUbp0B+cM1hFilwrOjGiDu4pj/ON63Vi7JPY5gkW6Ymqi8vXeNhdE/kpwC4k+bxPby92faAt9wzObOWpTd87HKSk5ttHqTCdAeeAzmWS41Ul+Y9OLdzZHbiLoneBvRasXW7ZyYrN/FAeHa9rV1qadOHkH+iPrtefeJLJCbJQEwEYrrcoII46OL7fI6EBugEi5YKqhlurgOCYV9WpmW3041Gr4uf76sULboXZDs+dhJTPTF8+CcmZ4h3DN43S9SEsZcqlWv8r4RyqceuvURbzDYwbxTYdUDHib6VDy5/55b1FUM2kWdDAyQdlka4zImr+eBmjFXFm/q2+H57n56/ZArQPq7QUKhttRSoU/z6Srjfk7EdiFI=
  - secure: GjoPpqb6oTn42iZJI3jFkwCpTMiVIhwepDSeDvoeUC/zgztjh9+5s/O5Nzqk6E5rkDYCiMe96y4/hTXQgm1ObnY+CdW9vcIn2coNL2Ko+UbzFcg0ngNRB6sVtGJbgjzcVAkszOf82Fos1FRayImXW4rtIXZShoBh3nPwWm4vop6goB1VPye1sXyIqltdK57jxPVBkFjC6HIk/9D5j9q7w8CqtUfmdltce+SsMEORnB2MNuWoHkLcHj+hBiROWVIRVaqkHO9xrxSkkC4mQ2FdMmyXL13D9DlsLO3UdoedWY2CRtmIuBFqzw5i+xSH1Z4UEsJuphx6Z8PZ0m7d18+YSpfzV5WgJ+klD9t4NJRMrL+1mwOIUHJ5v9S1v5NKMU8fFo93TEmvk+PGQp8yjkG1C+y5dHdqCMCePJVRTVUJXt7o0OWc3E+cfBFjfpW6GWVrNYufSdJAEm+F1ew7za7Hvq72Snm398UXj5H2BszelSiKXn5ygSjhoNVwbF5Lxt1LcipidvdXuBiHldiqWCOgjuTrSUee7qUc5oYWdA+MD8rUGpjlMt6QRGKImsMXqxiX/sQARsQxzBeBtPamcbenjdkAwm91/wYrJ8uqQKyM0Pm0Rc97LcjZOXXREh5fcGEIdZ2yo9iNaKzBNNtJF4BBLy3Q5YFXCNby4p31y9P7jYY=
